[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-multipart = "0.4"
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }
sanitize-filename = "0.3"
actix-cors = "0.6.4"
env_logger = "0.10.0"
clap = "3.0"
